version: '3.6'
services:
  app:
    build: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - "postgres"
    command: "/start-reload.sh"

  postgres:
    image: postgres:13.1
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4:2020-12-16-1
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin:/root/.pgadmin
    restart: unless-stopped

volumes:
  postgres:
  pgadmin: